--password-store=gnome
--ozone-platform-hint=auto
--ozone-platform=wayland
--gtk-version=4
--force-dark-mode
--enable-features=UseOzonePlatform,WebRTCPipeWireCapturer
--enable-webrtc-pipewire-capturer
