font_family JetBrainsMono Nerd Font
font_size 12.0

cursor_shape beam
cursor_blink_interval 0.5
scrollback_lines 20000

enable_audio_bell no
hide_window_decorations yes
confirm_os_window_close 0

# VLARCH_BG_OPACITY=0.85 — keep in sync with walker vlarch-nord theme
background_opacity 0.85
include theme.conf
