force_keyboard_focus = true
selection_wrap = true
theme = "vlarch-nord"
additional_theme_location = "~/.config/walker/themes"
hide_action_hints = true
hide_quick_activation = true
as_window = false
close_when_open = true

[shell]
exclusive_zone = -1
layer = "overlay"
anchor_top = true
anchor_bottom = true
anchor_left = true
anchor_right = true

[keybinds]
close = ["Escape"]
next = ["Down"]
previous = ["Up"]
quick_activate = []

[placeholders]
"default" = { input = "Search...", list = "No Results" }
"archlinuxpkgs" = { input = "Search packages...", list = "No packages found" }
"todo" = { input = "!> type a task…", list = "No todos — type !> task name, then Enter (or Ctrl+A, type, Enter)" }
"menus:themes" = { input = "Themes...", list = "No themes found" }

[providers]
max_results = 256
default = [
  "desktopapplications",
  "calc",
  "websearch",
]
empty = [
  "desktopapplications",
]

[[providers.prefixes]]
prefix = ";"
provider = "providerlist"

[[providers.prefixes]]
prefix = ">"
provider = "runner"

[[providers.prefixes]]
prefix = "/"
provider = "files"

[[providers.prefixes]]
prefix = "."
provider = "symbols"

[[providers.prefixes]]
prefix = "="
provider = "calc"

[[providers.prefixes]]
prefix = "@"
provider = "websearch"

[[providers.prefixes]]
prefix = ":"
provider = "clipboard"

[[providers.prefixes]]
prefix = ","
provider = "menus:keybinds"

[[providers.prefixes]]
prefix = "~"
provider = "menus:wifi"

[[providers.prefixes]]
prefix = "\\"
provider = "archlinuxpkgs"

[[providers.prefixes]]
prefix = "!"
provider = "todo"

[[providers.prefixes]]
prefix = "$"
provider = "menus:themes"

[providers.actions]
archlinuxpkgs = [
  { action = "install", bind = "Return", default = true },
  { action = "remove", bind = "Return" },
  { action = "show_all", label = "show all", bind = "ctrl i", after = "AsyncClearReload" },
  { action = "refresh", label = "refresh", bind = "ctrl r", after = "AsyncReload" },
  { action = "visit_url", label = "open URL", bind = "ctrl o" },
  { action = "show_installed", label = "show installed", bind = "ctrl i", after = "AsyncClearReload" },
]
todo = [
  { action = "save", default = true, bind = "Return", after = "AsyncClearReload" },
  { action = "save_next", label = "save & new", bind = "shift Return", after = "AsyncClearReload" },
  { action = "delete", bind = "ctrl d", after = "AsyncClearReload" },
  { action = "active", default = true, bind = "Return", after = "Nothing" },
  { action = "inactive", default = true, bind = "Return", after = "Nothing" },
  { action = "done", bind = "ctrl f", after = "Nothing" },
  { action = "change_category", bind = "ctrl y", label = "change category", after = "Nothing" },
  { action = "clear", bind = "ctrl x", after = "AsyncClearReload" },
  { action = "create", bind = "ctrl a", after = "AsyncClearReload" },
  { action = "search", bind = "ctrl a", after = "AsyncClearReload" },
]
