force_keyboard_focus = true
selection_wrap = true
theme = "vlarch-nord"
additional_theme_location = "~/.config/walker/themes"
hide_action_hints = true
hide_quick_activation = true

[keybinds]
close = ["Escape"]
next = ["Down"]
previous = ["Up"]
quick_activate = []

[placeholders]
"default" = { input = "Search...", list = "No Results" }

[providers]
max_results = 256
default = [
  "desktopapplications",
  "calc",
  "websearch",
]
empty = [
  "desktopapplications",
]

[[providers.prefixes]]
prefix = ";"
provider = "providerlist"

[[providers.prefixes]]
prefix = ">"
provider = "runner"

[[providers.prefixes]]
prefix = "/"
provider = "files"

[[providers.prefixes]]
prefix = "."
provider = "symbols"

[[providers.prefixes]]
prefix = "="
provider = "calc"

[[providers.prefixes]]
prefix = "@"
provider = "websearch"

[[providers.prefixes]]
prefix = ":"
provider = "clipboard"
