# Vlarch tmux config.

set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-kitty:RGB"
set -g escape-time 10
set -g focus-events on
set -g history-limit 50000
set -g mouse on
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind r source-file ~/.config/tmux/tmux.conf \; display "reloaded"

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

set -g status-position top
set -g status-style "bg=#1d2021,fg=#ebdbb2"
set -g status-left  " #S "
set -g status-right " %Y-%m-%d %H:%M "
setw -g window-status-current-style "fg=#1d2021,bg=#b8bb26"
